export enum ErrorCodes {
    SEARCH = 'PGPTE01',
    MENULOAD = 'PGPTE02',
    POPULARLOAD = 'PGPTE03',
    ASSIGN = 'PGPTE04',
    UNASSIGN = 'PGPTE05',
    FEATURELOAD = 'PGPTE06',
    FEEDBACKCREATE = 'PGPTE07',
    PROFILELOAD = 'PGPTE08',
    QANDALOAD = 'PGPTE09',
    DISCLAIMERLOAD = 'PGPTE10',
    SUITEBUDDIES = 'PGPTE11',
  }